### ISSUE TITLE
Modify the app to allow for an empty list and add the ability to add new contacts 

### ISSUE THREAD

**Issue by e2thed** [e2thed/mobile-class#2]
Based on the answer from the Professor, the app will start with an empty list. And so the ability to add a new contact will be essential for him to move forward with his testing.

**Comment by uneq95** [comment]
Is this completed or you need help completing this?

**Comment by e2thed** [comment]
This is in progress at the moment. Think I got it pretty close though.

**Comment by e2thed** [comment]
I got this worked out now. Thanks.
