### ISSUE TITLE
Add the ability to delete a contact from the app.

### ISSUE THREAD

**Issue by e2thed** [e2thed/mobile-class#3]
I can imagine deleting from the main view or the details view. The details view will be the easier to add without too many modifications. I'm thinking the deleting from list be treated as a secondary goal.

**Comment by uneq95** [comment]
its simple!! display a dialog after clicking a list item asking the user for deleting it. If the user chooses 'YES', then open database and execute delete query.Then update your list view with the new list.

**Comment by e2thed** [comment]
That would take care of the deleting issue from the main list. However, If I understand your recommendation, you are saying from the main list click on an item and then prompt for deleting? What if I only want to see the details? Would I need to go through the delete prompt each time?

**Comment by uneq95** [comment]
see...use onclick for displaying contact details and onlongclick for deleting the app.

**Comment by uneq95** [comment]
you can also put an option there in the contact details activity for deleting the contact

**Comment by e2thed** [comment]
Both really good suggestions. Thanks. I guess I had forgotten about the differences between the click and long click. nice.

**Comment by e2thed** [comment]
Based on the timing, I did not put the long click solution in the main view. I got the specs fleshed out for the basic crud operations. I did not go into "pop-up" windows either to focus more on the intents between the activities. There were a lot of paths that we can go with the app.
